ProductProject/appcore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('modules.ProductClient.ClientApp.urls',namespace='productclient')),
    path('account/',include('modules.AccountApp.urls',namespace='accountapp')),
    path('products/',include('modules.ProductApiApp.urls',namespace='productapiapp')),
    path('wishlist/',include('modules.wishlistapiapp.urls',namespace='wishlistapiapp')),
    path('admindashboard/',include('modules.ProductClient.AdminDashboard.urls',namespace='admindashboard')),
    path('cart/',include('modules.ProductClient.cartapp.urls',namespace='cartapp')), 
]

urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

ProductProject/modules/AccountApp/urls.py
from django.urls import path
from modules.AccountApp import views
# from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "accountapp"

urlpatterns = [
    path('registration', views.RegisterView.as_view(),name='registration'),
#    path('login/', auth_views.LoginView.as_view(template_name='account/signin.html'), name="login"),
#    path('logout/', auth_views.LogoutView.as_view(template_name='account/signout.html'), name='logout'),
   path('password-reset/', auth_views.PasswordResetView.as_view(template_name='account/registration/password_reset_form.html',
         subject_template_name='account/registration/password_reset_subject.txt', email_template_name='account/registration/password_reset_email.html', success_url=reverse_lazy('accountapp:password_reset_done')), name='password_reset'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='account/registration/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='account/registration/password_reset_confirm.html',success_url=reverse_lazy('productclientapp:login')), name='password_reset_confirm'),
   path('profile/', views.ProfileDetailView.as_view(), name='profile'),


   # login and logout api
   path('addUser/', views.Record.as_view(), name="register"),
   path('login/', views.Login.as_view(), name="login"),
   path('logout/', views.Logout.as_view(), name="logout"),

   # api enduser
   path('countuserproduct/',views.UserProductCountView.as_view(),name='count_user_product'),
   path('adminusers/',views.AdminUserListView.as_view(),name='admin_users'),
   path('normalusers/',views.NormalUserListView.as_view(),name='normal_users'),
   path('deactivatedusers/',views.DeactivatedUserListView.as_view(),name='deactivated_users_list'),
   path('changemodeuser/<int:pk>/',views.ChangeModeUserView.as_view(),name='changemode_user'),

]

ProductProject/modules/ProductClient/ClientApp/urls.py
from django.urls import path
from modules.ProductClient.ClientApp import views

app_name = "productclientapp"

urlpatterns = [
   path('',views.HomeView.as_view(),name='home'),

   # user login
   path('login/', views.LoginView.as_view(), name="login"),
   path('logout/', views.LogoutView.as_view(), name="logout"),


   path('aboutus/',views.AboutUsView.as_view(),name='about_us'),
   path('contact/',views.ContactView.as_view(),name='contact'),
   path('productlist/',views.ProductListView.as_view(),name='list_product'),
   path('productdetail/<slug:slug>/',views.ProductDetailView.as_view(),name='detail_product'),
   path('createwishitem/', views.CreateWishItemsView.as_view(),name='create_wish_item'),
   path('listwishitem/', views.ListWishItemsView.as_view(),name='list_wish_item'),
]

ProductProject/modules/ProductClient/cartapp/urls.py
from django.urls import path
from modules.ProductClient.cartapp import views
app_name = "cartapp"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

ProductProject/templates/client/partial/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap"
    rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title> 
        {% block title %}
        {% endblock %}
    </title>
    
    
    
    {% block styles %}
    {% endblock %}

    
</head>
<body style="font-family: sans-serif;">
    {% include 'client/partial/header.html' %}
    {% block content %}
    {% endblock %}
   
    {% include 'client/partial/footer.html' %}
    
    

</body>
</html>

ProductProject/templates/client/partial/basehome.html
{% extends 'client/partial/base.html' %}
{% load static %}
{% block style %}


{% endblock %}
{% block content %}
   {% block homecontent %}
   {% endblock %}
   {% include 'client/partial/footer.html' %}
{% endblock %}

ProductProject/templates/client/partial/footer.html
{% load static %}
<head> 
  <link rel="stylesheet" type="text/css" href="{% static 'css/client/footer.css' %}">
</head>
<footer class="text-center text-lg-start bg-dark text-white text-decoration-none ">
  <!-- Section: Social media -->
  <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
    
    <div class="container text-center text-md-start mt-4">
      <div class="row">
        <div class="col-sm-3">
          <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgmd2uAfYodCugIWKCFZsxYx4di4mCC_EYF7t2Fc_HDA&usqp=CAU&ec=48665699" style="height:80px;width:200px"/>
        </div>
        <div class="col-sm-9 text-end">
        <p class="mt-3">Product<span class="text-secondary"> © 2010 - 2023 All rights reserved.</span></p></div>
     </div><hr>
      <div class="row mt-5">
        <div class="col-md-4 col-lg-4 col-xl-4 mx-auto mb-5 mt-2">
          <p class=" text-secondary">
            Effective product descriptions can possibly lure potential customers. Good product descriptions can potentially influence a purchase decision. Great product descriptions can ultimately help improve conversion rates and increase sales, as well as boost your visibility and SEO on paid channels.

The technical details, including the use of power words and A/B tests, can be the difference between a potential buyer on your ecommerce website and those customers shopping at a competitor with similar products.


          </p><br>
          <p class="text-secondary">Think of rice, think of Product.</p>
        </div>
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto mb-4 mt-2">
          <ul>
             <li class="footer_link">
              <p>
                <a href="#" class="text-reset text-decoration-none"><span class="text-secondary">Home</span></a>
              </p>
            </li>
            <li class="footer_link">
              <p>
                <a href="#!" class="text-reset text-decoration-none"><span class="text-secondary">Product</span></a>
              </p>
            </li>
            <li  class="footer_link">
              <p>
                <a href="" class="text-reset text-decoration-none"><span class="text-secondary">Receipes</span></a>
              </p>
            </li>
            <li  class="footer_link">
              <p>
                <a href="#!" class="text-reset text-decoration-none"><span class="text-secondary">News/Blog</span></a>
              </p>
            </li>
            <li  class="footer_link">
              <p>
                <a href="" class="text-reset text-decoration-none"><span class="text-secondary">About Us</span></a>
              </p>
            </li>
            <li  class="footer_link">
              <p>
                <a href="" class="text-reset text-decoration-none"><span class="text-secondary">E-Brouchure</span></a>
              </p>
            </li>
            <li  class="footer_link">
              <p>
                <a href="" class="text-reset text-decoration-none"><span class="text-secondary">Contact Us</span></a>
              </p>
            </li>
          </ul>
        </div>
        <div class="col-md-4 col-lg-4 col-xl-3 mx-auto mt-2">
          <div class="row">
            <div class="col-md-1">
              <i class="fa fa-map-marker  me-2 location" style="font-size:28px"></i>
            </div>
            <div class="col-md-10 text-secondary">
              <p> 00 Ballygunge Circular Road,Room abc -
                xyz Building, Kolkata 700045
              West Bengal, INDIA </p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-1">
              <i class="fa fa-phone " style="font-size:28px"></i>
            </div>
            <div class="col-md-10 text-secondary">
              <p> 1800-3130-77777 <br>
              +91-33-46049826/27</p></p>
            </div>
          </div>
          <hr>
          <div class="row">
            <div class="col-md-1">
              <i class="fa fa-envelope" style="font-size:28px ;"></i>
            </div>
            <div class="col-md-10">
              <p class="ms-2 text-secondary">info@product.com</p>
            </div>   
          </div>
          <hr>
        </div>
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 card  ms-2 ">
          <h3 class="text-uppercase fw-bold mb-4 mt-3 ms-3">NEWSLETTER</h3>
          <i class="fa fa-newspaper-o ms-3 paper" style="font-size:34px"></i>
          <p class="mt-3 ms-3 text-secondary">
            Inspiring cooks and nourishing homes through delicious recipes, tips and other updates from product, right to your inbox.
          </p>
          <form>
            <input type="text" class="form-control text-secondary " name="" placeholder="Email address">
          </form>
          <hr>
          <button href="" class="btn btn-warning mt-3 ms-3 mb-4 text-white round">SUBSCRIBE</button>
        </div>
      </div>
    </div>
  </section>
</div>
</footer>

ProductProject/templates/client/partial/header.html
{% load static %}
<style>
  .logo {
    font-size: 100%;
    border: 0.1rem solid #fff;
    border-radius: 2rem;
    padding: 0.4em;
    box-shadow: 0 0 .7rem #fff,
        0 0 .7rem #fff,
        0 0 2rem SlateBlue,
        0 0 0.8rem SlateBlue,
        0 0 2.8rem SlateBlue,
        inset 0 0 6.3rem SlateBlue;
}
.navbar {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding: 15px;
    background-color: #0039c3;
    color: white;
    font-family: Serif;
}
.nav-link{
    color: #fff;
}
.nav-link:hover {
    background-color: SlateBlue;
    border-radius: 20px;
    transition: 0.1s ease;
    color: white;
    padding: 7px;
}
</style>
  <nav class=" navbar navbar-expand-lg nav-lower">
    
    <div class="container-fluid me-5">
      <div class="logo">PRODUCT COMPANY</div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 nav-fill w-50 ms-4">
          <li class="nav-item ">
            <a class="nav-link active text-white" aria-current="page" href="/">HOME</a>
          </li>
          <li class="nav-item ">
            <a class="nav-link " href="{% url 'productclientapp:list_product' %}" >  PRODUCTS  </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'productclientapp:about_us' %}">ABOUT US</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'productclientapp:contact' %}">CONTACT US</a>
        </li>
       
      </ul>
      <form class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0 nav-fill w-100">
        {% if request.session.user.is_staff %}
            <li class="nav-item">
                <a class="me-5 nav-link" href="{% url 'admindashboard:home' %}">DASHBOARD</a>
            </li>
        {% endif %}
        <li class="nav-item">
          <a class="me-5 nav-link" href="{% url 'cartapp:cart_detail' %}">Cart</a>
        </li>
        {% if request.session.user %}
            <li class="nav-item">
              <a class=" nav-link" href="{% url 'productclientapp:list_wish_item' %}">WishList</a>
          </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'accountapp:profile' %}">{{request.session.user.username}}</a>
            </li>
            <li class="nav-item">
                <a class="me-5 nav-link" href="{% url 'productclientapp:logout' %}">LOGOUT</a>
            </li>
            
        {% else %}
        <li class="nav-item">
            <a class="nav-link deactive" href="{% url 'productclientapp:login' %}">SIGNIN</a>
        </li>
        {% endif %}
        </ul>
      </form>
    </div>
  </div>
</nav>