ProductProject/appcore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('modules.ProductClient.ClientApp.urls',namespace='productclient')),
    path('account/',include('modules.AccountApp.urls',namespace='accountapp')),
    path('products/',include('modules.ProductApiApp.urls',namespace='productapiapp')),
    path('wishlist/',include('modules.wishlistapiapp.urls',namespace='wishlistapiapp')),
    path('admindashboard/',include('modules.ProductClient.AdminDashboard.urls',namespace='admindashboard')),
    path('cart/',include('modules.ProductClient.cartapp.urls',namespace='cartapp')), 
]

urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

ProductProject/modules/ProductClient/AdminDashboard/urls.py
from django.urls import path
from modules.ProductClient.AdminDashboard import views

app_name = "admindashboard"

urlpatterns = [
   path('',views.AdminDashboardView.as_view(),name='home'),

   # users urls
   path('adminusers',views.AdminUsersListDashboardView.as_view(),name='admin_user_list'),
   path('normalusers',views.NormalUsersListDashboardView.as_view(),name='normal_user_list'),
   path('deactivatedusers',views.DeactivatedUsersListDashboardView.as_view(),name='deactivated_user_list'),
   path('modechangeusers/<int:pk>/',views.ModeChangeUserDashboardView.as_view(),name='mode_change_user'),

   # wishlist urls
   path('wishlists/',views.WishListDashboardView.as_view(),name='wish_lists'),
   path('wishlistdelete/<slug:slug>/',views.WishDeleteDashboardView.as_view(),name='wish_listt_delete'),

   # product urls
   path('productlist/',views.ProductListDashboardView.as_view(),name='product_list'),
   path('productdelete/<slug:slug>/',views.ProductDeleteDashboardView.as_view(),name='product_delete'),
   path('productcreate/',views.ProductCreateDashboardView.as_view(),name='product_create'),

   # calender urls
   path('calender/',views.CalenderDashboardView.as_view(),name='calender'),
   path('maps/',views.MapsDashboardView.as_view(),name='maps'),
]

ProductProject/modules/ProductClient/ClientApp/urls.py
from django.urls import path
from modules.ProductClient.ClientApp import views

app_name = "productclientapp"

urlpatterns = [
   path('',views.HomeView.as_view(),name='home'),

   # user login
   path('login/', views.LoginView.as_view(), name="login"),
   path('logout/', views.LogoutView.as_view(), name="logout"),


   path('aboutus/',views.AboutUsView.as_view(),name='about_us'),
   path('contact/',views.ContactView.as_view(),name='contact'),
   path('productlist/',views.ProductListView.as_view(),name='list_product'),
   path('productdetail/<slug:slug>/',views.ProductDetailView.as_view(),name='detail_product'),
   path('createwishitem/', views.CreateWishItemsView.as_view(),name='create_wish_item'),
   path('listwishitem/', views.ListWishItemsView.as_view(),name='list_wish_item'),
]

ProductProject/modules/ProductClient/AdminDashboard/models.py
from django.db import models

# Create your models here.

ProductProject/modules/ProductClient/AdminDashboard/views.py
from django.shortcuts import render,redirect
from django.views import View
import requests
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

import json
from rest_framework.authtoken.models import Token

# Create your views here.


class AdminDashboardView(View):
    def get(self,request,*args,**kwargs):
        end_url = 'http://127.0.0.1:8000/account/countuserproduct/' 
        products = requests.get(end_url)
        context = products.json()['data']
        return render(request,'admindashboard/dashboard.html',context)

class AdminUsersListDashboardView(View):
    paginate_by = 5

    def get(self,request,*args,**kwargs):
        if 'user' in self.request.session and self.request.session['user']['is_staff']:
            auth_token = self.request.session['user']['token']
            headers = {'Authorization': f'Token {auth_token}'}
            end_url = 'http://127.0.0.1:8000/account/adminusers/' 
            products = requests.get(end_url,headers=headers)
            context = {
                'admin_users' : products.json()['data']
            }

            paginator = Paginator(context['admin_users'],self.paginate_by)
            page = self.request.GET.get('page')
            try:
                admin_user = paginator.page(page)
            except PageNotAnInteger:
                admin_user = paginator.page(1)
            except EmptyPage:
                admin_user = paginator.page(paginator.num_pages)  
            context['admin_users'] = admin_user

            return render(request,'admindashboard/users/adminusers.html',context)
        
        return redirect('admindashboard:home')

class NormalUsersListDashboardView(View):
    paginate_by = 5

    def get(self,request,*args,**kwargs):
        if 'user' in self.request.session and self.request.session['user']['is_staff']:
            auth_token = self.request.session['user']['token']
            headers = {'Authorization': f'Token {auth_token}'}
            end_url = 'http://127.0.0.1:8000/account/normalusers/' 
            products = requests.get(end_url,headers=headers)
            context = {
                'normal_users' : products.json()['data']
            }

            paginator = Paginator(context['normal_users'],self.paginate_by)
            page = self.request.GET.get('page')
            try:
                normal_user = paginator.page(page)
            except PageNotAnInteger:
                normal_user = paginator.page(1)
            except EmptyPage:
                normal_user = paginator.page(paginator.num_pages)  
            context['normal_users'] = normal_user

            return render(request,'admindashboard/users/normalusers.html',context)

        return redirect('admindashboard:home')

class DeactivatedUsersListDashboardView(View):
    paginate_by = 5

    def get(self,request,*args,**kwargs):
        if 'user' in self.request.session and self.request.session['user']['is_staff']:
            auth_token = self.request.session['user']['token']
            headers = {'Authorization': f'Token {auth_token}'}
            end_url = 'http://127.0.0.1:8000/account/deactivatedusers/' 
            products = requests.get(end_url,headers=headers)
            context = {
                'deactivate_users' : products.json()['data']
            } 
            paginator = Paginator(context['deactivate_users'],self.paginate_by)
            page = self.request.GET.get('page')
            try:
                deactivate_user = paginator.page(page)
            except PageNotAnInteger:
                deactivate_user = paginator.page(1)
            except EmptyPage:
                deactivate_user = paginator.page(paginator.num_pages)  
            context['deactivate_users'] = deactivate_user

            return render(request,'admindashboard/users/deactivatedusers.html',context)

        return redirect('admindashboard:home')
        

class ModeChangeUserDashboardView(View):
    def get(self,request,pk,*args,**kwargs):
        if 'user' in self.request.session and self.request.session['user']['is_staff']:
            auth_token = self.request.session['user']['token']
            headers = {'Authorization': f'Token {auth_token}'}
            mode = self.request.GET.get('mode',None)
            end_url = 'http://127.0.0.1:8000/account/changemodeuser/' +str(pk)+'?mode='+mode
            products = requests.get(end_url,headers=headers)
            context = products.json()
            if mode == 'deactivate' or mode == 'staff':
                return redirect('admindashboard:normal_user_list')
            if mode == 'activate':
                return redirect('admindashboard:deactivated_user_list')
            if mode == 'normaluser':
                return redirect('admindashboard:admin_user_list')

        return redirect('admindashboard:home')


class WishListDashboardView(View):
    paginate_by = 5

    def get(self,request,*args,**kwargs):
        if 'user' in self.request.session:
            context = {}
            auth_token = self.request.session['user']['token']
            headers = {'Authorization': f'Token {auth_token}'}
            end_url = end_url = 'http://127.0.0.1:8000/wishlist/adminlist/' 
            wish_items = requests.get(end_url,headers=headers)
            if wish_items:
                context['wish_items'] =  wish_items.json()['data']
                

                paginator = Paginator(context['wish_items'],self.paginate_by)
                page = self.request.GET.get('page')
                try:
                    wish_item = paginator.page(page)
                except PageNotAnInteger:
                    wish_item = paginator.page(1)
                except EmptyPage:
                    wish_item = paginator.page(paginator.num_pages)  
                context['wish_items'] = wish_item
        return render(request,'admindashboard/wishlist/adminwishlist.html',context)

class WishDeleteDashboardView(View):
    def get(self,request,slug,*args,**kwargs):
        if 'user' in self.request.session:
            auth_token = self.request.session['user']['token']
            headers = {'Authorization': f'Token {auth_token}'}
            end_url = end_url = 'http://127.0.0.1:8000/wishlist/delete/' + slug + '/'
            wish_items = requests.delete(end_url,headers=headers)
            context = {
                'wish_items':wish_items.json()
            }

        return redirect('admindashboard:wish_lists')


class ProductListDashboardView(View):
    paginate_by = 5

    def get(self,request,*args,**kwargs):
        context = {}
        end_url = end_url = 'http://127.0.0.1:8000/products/list/'
        products = requests.get(end_url)
        if products:
            context = {
                'products':products.json()['data']
            }
            paginator = Paginator(context['products'],self.paginate_by)
            page = self.request.GET.get('page')
            try:
                product = paginator.page(page)
            except PageNotAnInteger:
                product = paginator.page(1)
            except EmptyPage:
                product = paginator.page(paginator.num_pages)  
                
            context['products'] = product
        return render(request,'admindashboard/product/list.html',context)

class ProductDeleteDashboardView(View):
    def get(self,request,slug,*args,**kwargs):
        if 'user' in self.request.session:
            auth_token = self.request.session['user']['token']
            headers = {'Authorization': f'Token {auth_token}'}
            end_url = end_url = 'http://127.0.0.1:8000/products/delete/' + slug + '/'
            products = requests.delete(end_url, headers=headers)
        return redirect('admindashboard:product_list')

class ProductCreateDashboardView(View):
    def get(self,request,*args,**kwargs): 
        print("66666666666666666666666") 
        if 'user' in self.request.session:
            print("4444444444444444444")
            auth_token = self.request.session['user']['token']
            headers = {'Authorization': f'Token {auth_token}'}
            dummy = json.loads(open("dummydata.json","rb").read())
            end_url = 'http://127.0.0.1:8000/products/create/'
            for d in dummy:
                data = {
                    'image_url' : d['image'],
                    'name' : d['name'],
                    'price' : d['price'],
                    'stock' : d['stock'],
                    'description' : d['description'],
                    'category' : d['category']
                }
                products = requests.post(end_url,headers=headers, data= data)
        return redirect('admindashboard:product_list')

class CalenderDashboardView(View):
    def get(self,request,*args,**kwargs):
        return render(request,'admindashboard/calender/admincalender.html')

class MapsDashboardView(View):
    def get(self,request,*args,**kwargs):
        return render(request,'admindashboard/maps.html')

ProductProject/templates/admindashboard/partial/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700&display=swap"
    rel="stylesheet"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta2/css/all.min.css" integrity="sha512-YWzhKL2whUzgiheMoBFwW8CKV4qpHQAEuvilg9FAn5VJUDwKZZxkJNuGM4XkWuk94WCrrwslk8yWNGmY1EduTA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link
      rel="stylesheet"
      href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous" />

    <title> 
        {% block title %}
        {% endblock %}
    </title>
    
    
    
    {% block styles %}
    {% endblock %}

    
</head>
<body style="font-family: sans-serif;">
    <!-- {% include 'admindashboard/partial/sidebar.html' %} -->
    <div class="container-fluid">
        <div class="row flex-nowrap">
          <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-secondary min-vh-100 border">
                {% include 'admindashboard/partial/sidebar.html' %}
                <hr />
            </div>
          </div>
          <div class="col py-3 bg-light">
            {% include 'admindashboard/partial/navbar.html' %}
            {% block content %}{% endblock %}
          </div>
        </div>
      </div>      
        
</body>
</html>

ProductProject/templates/admindashboard/partial/index.html
{% extends 'admindashboard/partial/base.html' %} {% load static %} &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
{% block title %} Dashboard {% endblock title %} {% block content %}
<div class="container-fluid">
  <div class="row flex-nowrap">
    <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0">
      <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-primary min-vh-100">
        
        <h5 class="lh-1 mB-0 logo-text mt-4 mb-4">Welcome Admin</h5>
        
        <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start ms-4" id="menu">
          <li>
            <a href="/" class="nav-link px-0 align-middle">
                <i class="fa fa-home" style="color:blue"></i>
              <span class="ms-1 d-none d-sm-inline">Dashboard</span>
            </a>
          </li>
          <li>
            <a href="" class="nav-link px-0 align-middle">
                <i class='far fa-user-circle' style="color:blue"></i>
              <span class="ms-1 d-none d-sm-inline ">Admin Users</span></a>
          </li>
          <li>
            <a href="" class="nav-link px-0 align-middle">
                <i class='fas fa-user-alt' style="color:blue"></i>
              <span class="ms-1 d-none d-sm-inline">Normal Users</span></a>
          </li>
          <li>
            <a href="" class="nav-link px-0 align-middle">
                <i class='fa fa-product-hunt' style="color:blue"></i>
              <span class="ms-1 d-none d-sm-inline ">Product</span></a>
          </li>
          <li>
            <a href="" class="nav-link px-0 align-middle">
                <i class="fab fa-pagelines" style="color:blue"></i>
              <span class="ms-1 d-none d-sm-inline ">Pages</span>
            </a>
          </li>
          <li>
            <a href="" class="nav-link px-0 align-middle">
                <i class="far fa-map" style="color:blue"></i>
              <span class="ms-1 d-none d-sm-inline">Maps</span>
            </a>
          </li>
           <li>
            <a href="" class="nav-link px-0 align-middle">
                <i class="far fa-calendar" style="color:blue"></i>
              <span class="ms-1 d-none d-sm-inline ">Calender</span>
            </a>
          </li>
        </ul>
        <hr />
      </div>
    </div>
    <div class="col py-3 bg-light">{% block contentbody %}{% endblock %}</div>
  </div>
</div>
{% endblock %}

ProductProject/templates/admindashboard/partial/navbar.html
<nav class="navbar navbar-expand-sm border-bottom">
    <div class="container-fluid"> 
    <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgmd2uAfYodCugIWKCFZsxYx4di4mCC_EYF7t2Fc_HDA&usqp=CAU&ec=48665699" alt="Snow" style="width:20%;height: 90px;">
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#mynavbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="d-flex">
        <div class="collapse navbar-collapse" id="mynavbar">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <a class="nav-link btn btn-outline-primary me-2" href="{% url 'productclientapp:home' %}">Goto main site</a>
            </li>
            <li class="nav-item">
              <a class="nav-link btn btn-outline-primary me-2" href="{% url 'productclientapp:logout' %}">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
          

ProductProject/templates/admindashboard/partial/sidebar.html
<section class="border-bottom w-100">
<h5 class="lh-1 mB-0 logo-text mt-5 ms-3 mb-4">Welcome Admin</h5>
</section>
<ul class="nav nav-pills flex-column mb-sm-auto mb-2 align-items-center align-items-sm-start ms-4">
    <li class="mt-3">
        <a href="{% url 'admindashboard:home' %}" class="nav-link px-0 align-middle">
        <i class="fa fa-home" style="color:blue"></i>
        <span class="ms-1 d-none d-sm-inline text-secondary">Dashboard</span>
        </a>
    </li>
    <li class="mt-2">
        <a href="{% url 'admindashboard:admin_user_list' %}" class="nav-link px-0 align-middle">
        <i class='far fa-user-circle' style="color:blue"></i>
        <span class="ms-1 d-none d-sm-inline text-secondary">Admin Users</span></a>
    </li>
    <li class="mt-2">
        <a href="{% url 'admindashboard:normal_user_list' %}" class="nav-link px-0 align-middle">
        <i class='fas fa-user-alt' style="color:blue"></i>
        <span class="ms-1 d-none d-sm-inline text-secondary">Normal Users</span></a>
    </li>
    <li class="mt-2">
        <a href="{% url 'admindashboard:deactivated_user_list' %}" class="nav-link px-0 align-middle">
        <i class='fas fa-user-alt text-danger'></i>
        <span class="ms-1 d-none d-sm-inline text-secondary">Deactivated Users</span></a>
    </li>
    <li class="mt-2">
        <a href="{% url 'admindashboard:product_list' %}" class="nav-link px-0 align-middle">
        <i class='fab fa-product-hunt text-primary' ></i>
        <span class="ms-1 d-none d-sm-inline text-secondary">Product</span></a>
    </li>
    <li class="mt-2">
        <a href="{% url 'admindashboard:wish_lists' %}" class="nav-link px-0 align-middle">
            <i class="fas fa-heart text-primary" ></i>
        <span class="ms-1 d-none d-sm-inline text-secondary">WishList</span></a>
    </li>
  
    <li class="mt-2">
        <a href="{% url 'admindashboard:maps' %}" class="nav-link px-0 align-middle">
        <i class="far fa-map" style="color:blue"></i>
        <span class="ms-1 d-none d-sm-inline text-secondary">Maps</span>
    </a>
    </li>
    <li class="mt-2">
        <a href="{% url 'admindashboard:calender' %}" class="nav-link px-0 align-middle">
        <i class="far fa-calendar" style="color:blue"></i>
        <span class="ms-1 d-none d-sm-inline text-secondary">Calender</span>
    </a>
    </li>
</ul>
<hr />
        