ProductProject/appcore/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('modules.ProductClient.ClientApp.urls',namespace='productclient')),
    path('account/',include('modules.AccountApp.urls',namespace='accountapp')),
    path('products/',include('modules.ProductApiApp.urls',namespace='productapiapp')),
    path('wishlist/',include('modules.wishlistapiapp.urls',namespace='wishlistapiapp')),
    path('admindashboard/',include('modules.ProductClient.AdminDashboard.urls',namespace='admindashboard')),
    path('cart/',include('modules.ProductClient.cartapp.urls',namespace='cartapp')), 
]

urlpatterns += static(settings.MEDIA_URL,
                        document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL,
                        document_root=settings.STATIC_ROOT)

ProductProject/modules/ProductClient/ClientApp/urls.py
from django.urls import path
from modules.ProductClient.ClientApp import views

app_name = "productclientapp"

urlpatterns = [
   path('',views.HomeView.as_view(),name='home'),

   # user login
   path('login/', views.LoginView.as_view(), name="login"),
   path('logout/', views.LogoutView.as_view(), name="logout"),


   path('aboutus/',views.AboutUsView.as_view(),name='about_us'),
   path('contact/',views.ContactView.as_view(),name='contact'),
   path('productlist/',views.ProductListView.as_view(),name='list_product'),
   path('productdetail/<slug:slug>/',views.ProductDetailView.as_view(),name='detail_product'),
   path('createwishitem/', views.CreateWishItemsView.as_view(),name='create_wish_item'),
   path('listwishitem/', views.ListWishItemsView.as_view(),name='list_wish_item'),
]

ProductProject/modules/ProductClient/cartapp/urls.py
from django.urls import path
from modules.ProductClient.cartapp import views
app_name = "cartapp"

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/',views.cart_add,name='cart_add'),
    path('remove/<int:product_id>/',views.cart_remove,name='cart_remove'),
]

ProductProject/templates/client/products/detail.html
{% extends 'client/partial/base.html' %}
{% load static %}
{% block title %}
Product Detail
{% endblock %}
{% block content %}

<section class="mt-5 mb-5">
    <div class="container justify-content-center mt-4">
        <div class="row">
            <div class="col-sm-8 ms-5">
                <img src="{% if product.image %}{{product.image}}{% endif %}" style="height:500px;width:100vh;"></img>
            </div>
        </div>
    </div>
<div class="container mt-4">
    <p style="font-weight: 700;color: orangered;font-size: 30px;">{{product.name}}</p>  
    <hr style="width: 15%;"> 
    
    <div class="row align-items-start mb-4" style="height:50%;">
      <div class="col-md-7">
      <div class="row">
      <div class="col">
        <p> Category : {{product.category}}</p>
              <p>Stock : {{product.stock}}</p>
              
        </div>
        
      </div>
              <h5>Descripton</h5>
              <p>{{product.description}}</p>
      </div>
  
      <div class="col-5 ">
        
         <hr style="width: 65%;">
  
  
          <p>  Cost :  R${{product.price}} </p>
          
          <div class="col-auto">
            <form action="{% url 'cartapp:cart_add' product.id %}" method="post">
              {{ cart_product_form }}
              {% csrf_token %}
              <input class="btn btn-primary text-white" type="submit" value="Add to cart">
          </form>
          </div>
       


      </div>
      </div>
</div>
</section>
{% endblock %}

ProductProject/templates/client/products/homeproductlist.html
<div class="container-fluid justify-content-center mt-1">
    <div class="row">
      {% for product1 in product.products|slice:":5" %}
     
      <div class="card me-1 " style="width:14rem">
      <a class="card-text float-right text-decoration-none" style="font-size: 0.9rem" href="{% url 'productclientapp:detail_product' slug=product1.slug %}" >
      <img src="{% if product1.image %}{{ product1.image }}{% else %}{{product1.image_url}}{% endif %}" class="card-img-top mt-2" style="height:200px;width:100%;">
        <div class="card-body">
          <p class="card-text text-danger" style="font-size: 0.9rem">
            {{product1.name}} <span>{% if request.session.user.username %}
         
                {% if product1.id in wish_list %}
                  <a class="float-end"  href="{% url 'productclientapp:create_wish_item' %}?product_id={{product1.id}}"> <i class="fa fa-heart text-danger"></i></a>
                 
                  {% else %}
                  <a class="float-end" href="{% url 'productclientapp:create_wish_item' %}?product_id={{product1.id}}"> <i class="fa fa-heart-o text-primary"></i></a>
                
                  {% endif %}
                
               {% endif %}</span> <br>
            stock - {{product1.stock}}
          </p>
          <p class="card-title h6 text-truncate text-secondary"><b>{{property.property.property_name}}</b></p>
          <p class="card-text" style="font-size: 0.9rem">
            R${{product1.price}} 
          </p>
        </a>
        <form action="{% url 'cartapp:cart_add' product1.id %}" method="post">
            <span class="d-none">{{ cart_product_form }}</span>
            {% csrf_token %}
            <input class="btn btn-outline-primary text-primary float-start mt-0" type="submit" value="Add to cart">
        </form>
        </div>
         
         
      </div>

      {% endfor %}
    </div>
  </div>
  
  

ProductProject/templates/client/products/list.html
{% extends 'client/partial/base.html' %}
{% load static %}
{% block title %}
Product List
{% endblock %}

{% block content %}
<!-- Carousel -->
<section class="mt-5 mb-2">
    <div class="container">
        <div class="row">
      <div class="col-sm-4">
      <h4 class="ml-4">List Of Products</h4>
      </div>
      <div class="col-sm-8 d-flex justify-content-end" >
       <form action="">
      <div class="input-group">
        <input type="search" class="form-control rounded mt-2 me-1" name="product" placeholder="Product Name" aria-label="Search" aria-describedby="search-addon" />
        <button class="btn btn-primary mt-2"><i class="fas fa-search text-white"></i></button>
      </div>
       </form>
       </div>
      </div>
      </div>
      
      <div class="container justify-content-center mt-4 mb-4 " >
        <div class="row justify-content-center">
          {% if not products %}
          <p class="text-center"> No product found.</p>
       
        {% endif %}
        {% include 'client/paginations/pagination.html' %}
          {% for product in products %}
          <div class="card me-2 mt-4" style="height:300px;width:100vh;">    
          <div class="card-body row">
          <div class="col-sm-5">
           <a class="card-text float-right text-decoration-none" style="font-size: 0.9rem" href="" >
          <img src="{% if product.image %}{{ product.image }}{% else %}{{product.image_url}}{% endif %}" class="card-img-top mt-2" style="height:240px;width:400px;"/>
          </a>
          </div>
          <div class="col-sm-6 ms-5 mt-1">
            <p class="card-title h6 ml-1">{{product.name}} 
            </p>
              <p class="card-text text-danger" style="font-size: 1rem">
                <b> {{product.description}}</b> <br>
                <b>Stock - {{product.stock}} </b> <br>
                  
              </p>
              
              <p class="card-text" style="font-size: 1rem">
                Price -  R${{product.price}} 
              </p>
              
                <form action="{% url 'cartapp:cart_add' product.id %}" method="post">
                  <span class="d-none">{{ cart_product_form }}</span>
                  {% csrf_token %}
                  <input class="btn btn-outline-primary text-primary float-start me-3" type="submit" value="Add to cart">
              </form>
              
  
               {% if request.session.user.username %}
               
                {% if product.id in wish_list %}
                  <a class="float-start" style="font-size:24px" href="{% url 'productclientapp:create_wish_item' %}?product_id={{product.id}}"> <i class="fa fa-heart text-danger"></i></a>
                 
                  {% else %}
                  <a class="float-start" style="font-size:24px" href="{% url 'productclientapp:create_wish_item' %}?product_id={{product.id}}"> <i class="fa fa-heart-o text-primary"></i></a>
                
                  {% endif %}
                
               {% endif %}
              <a class="card-text float-end text-decoration-none" style="font-size:1.5rem" href="{% url 'productclientapp:detail_product' slug=product.slug %}" >
                Show Details
              </a>
            </div>
             
            </div>
              
          </div>
          {% endfor %}
          {% include 'client/paginations/pagination.html' %}
        </div>
        
      </div>
</section>
{% endblock %}